import gallery from "../../public/data/gallery.json";
import videos from "../../public/data/videos.json";

const EMOJI: Record<string, string> = {
  wedding: "🥂", newborn: "👶", baby: "🧸", family: "👨‍👩‍👧", travel: "✈️", brand: "🚀",
  elders: "👴", anniversary: "💍", product: "📦", memorial: "🕯️", pet: "🐾",
};

export default function Gallery() {
  const items = (gallery as any[]) || [];
  const films = (videos as any[]) || [];

  return (
    <section id="examples" className="py-24 px-6 bg-[--bg] border-t border-[--border]">
      <div className="max-w-6xl mx-auto">
        <p className="mono text-xs uppercase tracking-[0.3em] text-[--accent] mb-3 text-center">
          what you can make
        </p>
        <h2 className="text-3xl md:text-5xl font-black tracking-tight text-center mb-3">
          Stories people can feel
        </h2>
        <p className="text-center text-[--muted] max-w-xl mx-auto mb-12">
          Cinematic images and films generated by 7stories — pick a category,
          paste your story, and get results like these.
        </p>

        {/* Cinematic films (auto-playing, muted) */}
        {films.length > 0 && (
          <>
            <p className="mono text-xs uppercase tracking-[0.3em] text-[--muted] mb-4">🎬 Cinematic films</p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-12">
              {films.map((v, i) => (
                <figure key={i} className="card overflow-hidden group relative aspect-video">
                  <video
                    src={v.video}
                    muted
                    loop
                    playsInline
                    autoPlay
                    preload="none"
                    className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                  />
                  <figcaption className="absolute bottom-0 inset-x-0 p-3 bg-gradient-to-t from-black/80 to-transparent flex items-center gap-2">
                    <span className="text-lg">{EMOJI[v.cat] || "🎬"}</span>
                    <span className="font-semibold text-white text-sm">{v.label}</span>
                    <span className="ml-auto text-[10px] uppercase tracking-widest text-white/70 mono">
                      {v.model.split("/").pop()}
                    </span>
                  </figcaption>
                </figure>
              ))}
            </div>
          </>
        )}

        {/* Image grid with 3D hover tilt */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {items.map((g, i) => (
            <figure key={i} className="card overflow-hidden group relative aspect-[4/3] hover:rotate-[0.5deg] hover:-translate-y-1 hover:border-[--accent]/40 hover:shadow-[0_20px_50px_-20px_rgba(139,124,255,0.4)] transition-all duration-300">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={g.image}
                alt={g.label}
                loading="lazy"
                decoding="async"
                className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
              />
              <figcaption className="absolute bottom-0 inset-x-0 p-3 bg-gradient-to-t from-black/80 to-transparent flex items-center gap-2">
                <span className="text-xl">{EMOJI[g.cat] || "✨"}</span>
                <span className="font-semibold text-white">{g.label}</span>
                <span className="ml-auto text-[10px] uppercase tracking-widest text-white/60 mono">cinematic</span>
              </figcaption>
            </figure>
          ))}
        </div>
      </div>
    </section>
  );
}
