import gallery from "../../public/data/gallery.json";

export default function Gallery() {
  const items = (gallery as any[]) || [];
  if (!items.length) return null;
  return (
    <section id="examples" className="py-24 px-6 bg-[--bg] border-t border-[--border]">
      <div className="max-w-6xl mx-auto">
        <p className="mono text-xs uppercase tracking-[0.3em] text-[--accent] mb-3 text-center">
          what you can make
        </p>
        <h2 className="text-3xl md:text-5xl font-black tracking-tight text-center mb-3">
          Stories people can feel
        </h2>
        <p className="text-center text-[--muted] max-w-xl mx-auto mb-12">
          Cinematic images and films generated by 7stories — pick a category,
          paste your story, and get results like these.
        </p>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          {items.map((g, i) => (
            <figure key={i} className="card overflow-hidden group relative">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={g.image}
                alt={g.label}
                className="w-full aspect-[4/3] object-cover transition-transform duration-500 group-hover:scale-105"
              />
              <figcaption className="absolute bottom-0 inset-x-0 p-4 bg-gradient-to-t from-black/80 to-transparent flex items-center gap-2">
                <span className="text-2xl">
                  {({ wedding: "🥂", newborn: "👶", family: "👨‍👩‍👧", travel: "✈️", brand: "🚀", baby: "🧸" } as any)[g.cat] || "✨"}
                </span>
                <span className="font-semibold text-white">{g.label}</span>
                <span className="ml-auto text-[10px] uppercase tracking-widest text-white/60 mono">
                  cinematic
                </span>
              </figcaption>
            </figure>
          ))}
        </div>
      </div>
    </section>
  );
}
